### ISSUE TITLE
`evaluate.js` example fails in headless mode

### ISSUE THREAD

**Issue by imiric** [grafana/xk6-browser#536]
On current `main` (96b89a1), Chromium 104.0.5112.79 and Linux, running the [`evaluate.js` example](https://github.com/grafana/xk6-browser/blob/96b89a1d0ad8d2f73d79550545bc61d786a90715/examples/evaluate.js) fails the `width` check, but only when run in headless mode.

Headless:
```
$ XK6_BROWSER_LOG=info XK6_HEADLESS=1 xk6 run -q examples/evaluate.js
INFO[0001] {"deviceScaleFactor":1,"height":720,"width":1280}  source=browser-console-api

     ✗ width
      ↳  0% — ✓ 0 / ✗ 1
     ✓ height
     ✓ scale
```

Headed:
```
$ XK6_BROWSER_LOG=info xk6 run -q examples/evaluate.js
INFO[0001] {"deviceScaleFactor":1,"height":720,"width":1265}  source=browser-console-api

     ✓ width
     ✓ height
     ✓ scale
```

Notice that the returned width is 1280 in headless, but 1265 in headed.

This might be a recent regression, or a change in Chromium(?), since it worked a few months ago.

You can see the failure in CI as well: [job #1147](https://github.com/grafana/xk6-browser/actions/runs/3069371391/jobs/4957938788). The reason it still passes is because failing checks still exit the process with 0. So we need a better way of ensuring we catch these issues in CI...

**Comment by mstoykov** [comment]
I did bisect this to 3cb501b4074cd87c4e3846ced54b0cc2d3d48a12. 

The problem is the addition of `f["hide-scrollbars"] = true` when running headless - dropping it fixes the test.

Now the question is should we fix the test to change the expected width or fix the option?

This is what playwright does ... and I guess we are just copying playwright in most regards? So I guess the test should be fixed?

Btw it seems like playwright has a way to disable default arguments like this one. And I don't think this is possible for us in this case :thinking:

**Comment by imiric** [comment]
Nice find! :clap:

I also think it makes more sense to update the test. We should follow Playwright's behavior whenever possible, and there's no reason to not do that in this case.

> Btw it seems like playwright has a way to disable default arguments like this one. And I don't think this is possible for us in this case

How so? With a CLI flag or something?

**Comment by mstoykov** [comment]
> How so? With a CLI flag or something? 

Turns out we have documented it but have not actually implement it ... see https://github.com/grafana/xk6-browser/pull/547

**Comment by inancgumus** [comment]
Nice 👏  However, I'm still getting an error even if we ignore the `--hide-scrollbars` flag 😒 🤔 

```
// running this with #547 fix

$ kbr examples/evaluate.js
...
go: finding module for package go.k6.io/k6/cmd
go: found go.k6.io/k6/cmd in go.k6.io/k6 v0.40.0
...
INFO[0001] {"deviceScaleFactor":1,"height":720,"width":1280}  source=browser-console-api

     ✗ width
      ↳  0% — ✓ 0 / ✗ 1
     ✓ height
     ✓ scale
```
